Repository openego/eGon-data, pull requests merged in 2021-03, with the labels that each got.

#125 Features/#122 create powerplant table
  src/egon/data/airflow/dags/pipeline.py
  src/egon/data/processing/power_plants/__init__.py
Labels: :building_construction: integration

#135 Features/#9 migrate substation section
  CHANGELOG.rst
  setup.py
  src/egon/data/airflow/dags/pipeline.py
  src/egon/data/datasets.yml
  src/egon/data/processing/substation/__init__.py
  src/egon/data/processing/substation/ehv_substation.sql
  src/egon/data/processing/substation/hvmv_substation.sql
Labels: :building_construction: integration

#149 Features/#101 import heat demand data
  CHANGELOG.rst
  README.rst
  setup.py
  src/egon/data/airflow/dags/pipeline.py
  src/egon/data/airflow/entrypoints/create_postgis_extension.sql
  src/egon/data/datasets.yml
  src/egon/data/importing/heat_demand_data/__init__.py
  src/egon/data/importing/heat_demand_data/raster2cells-and-centroids.sql
  src/egon/data/importing/heat_demand_data/scenarios_HD_raster_adjustments.csv
Labels: :building_construction: integration

#141 Features/#47 integrate demographic model
  CHANGELOG.rst
  setup.py
  src/egon/data/airflow/dags/pipeline.py
  src/egon/data/datasets.yml
  src/egon/data/processing/zensus/__init__.py
Labels: :building_construction: integration

#152 Features/#148 drop python36 support
  .github/workflows/build.yml
  CHANGELOG.rst
  setup.py
  tox.ini
Labels: :bug: bug, :test_tube: testing

#156 Include substation's dependence on vg250 in pipeline
  src/egon/data/airflow/dags/pipeline.py
Labels: :bug: bug

#158 Features/#157 adjust heat demand import
  CHANGELOG.rst
  src/egon/data/importing/heat_demand_data/__init__.py
Labels: :bug: bug

#172 Hotfixes/#171 substation sequence
  CHANGELOG.rst
  src/egon/data/processing/substation/__init__.py
Labels: :bug: bug

#173 Features/#167 adjust heat demand in unpopulated cells
  CHANGELOG.rst
  src/egon/data/airflow/dags/pipeline.py
  src/egon/data/importing/heat_demand_data/__init__.py
  src/egon/data/importing/heat_demand_data/raster2cells-and-centroids.sql
Labels: :building_construction: integration

#182 Delete zensus-inside-germany tables only if they exist
  CHANGELOG.rst
  src/egon/data/processing/zensus_vg250/zensus_population_inside_germany.py
Labels: :bug: bug

#186 Add gdal to pre-requisites
  CHANGELOG.rst
  README.rst
Labels: :book: docs

#180 Features/#165 centralize map zensus to boundaries
  CHANGELOG.rst
  src/egon/data/airflow/dags/pipeline.py
  src/egon/data/datasets.yml
  src/egon/data/processing/zensus/__init__.py
  src/egon/data/processing/zensus_vg250/zensus_population_inside_germany.py
Labels: :building_construction: integration
